# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run setup-dgmjrsdk
      uses: dgmjr-actions/setup-dgmjrsdk@main
      with:
        git-token: ${{ secrets.GITHUB_TOKEN }}
        environment: Release
        git-nuget-endpoint: ${{ vars.GIT_NUGET_ENDPOINT }}
        private-nuget-endpoint: ${{ vars.DGMJR_IO_NUGET_ENDPOINT }}
    - name: Restore dependencies
      run: dotnet restore src/DgmjrSdk.nuproj
    - name: Build
      run: dotnet build src/DgmjrSdk.nuproj --no-restore -c:Release
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
