# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: CI-Build
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: Checkout the repository being compiled
    #   uses: dgmjr-actions/git-checkout@main
    #   with:
    #     path: Repo
    #     token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Checkout the Packages repository alongside the one being compiled
    #   uses: dgmjr-actions/git-checkout@main
    #   with:
    #     repository: dgmjr-io/Packages
    #     path: Packages
    #     token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run setup-dgmjrsdk
      uses: dgmjr-actions/setup-dgmjrsdk@main
      with:
        git-token: ${{ secrets.GITHUB_TOKEN }}
        environment: Release
        git-nuget-endpoint: ${{ vars.GIT_NUGET_ENDPOINT }}
        private-nuget-endpoint: ${{ vars.FEEDZ_IO_ENDPOINT_URL }}
        private-nuget-api-key: ${{ secrets.FEEDZ_IO_TOKEN }}
        repo: dgmjr-io/DgmjrSdk
    - name: Pack
      run: dotnet build Repo/src/DgmjrSdk.csproj -c:Release
    - name: Upload the NuGet Package
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: DgmjrSdk-NuGetPackage
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/*.nupkg"
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        retention-days: 1
        
  push-nuget:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run nuget-push
      uses: dgmjr-actions/nuget-push@main
      with:
        git-token: ${{ secrets.GITHUB_TOKEN }}
        project-file-path: Repo/src/DgmjrSdk.csproj
        environment: Release
        git-nuget-endpoint: ${{ vars.GIT_NUGET_ENDPOINT }}
        private-nuget-endpoint: ${{ vars.FEEDZ_IO_ENDPOINT_URL }}
        private-nuget-api-key: ${{ secrets.FEEDZ_IO_TOKEN }}
        repo: dgmjr-io/DgmjrSdk
        push-github: true
        push-dgmjr-io: true
        push-nuget: false
