# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository being compiled
      uses: actions/checkout@v3
      with:
        path: Repo
    - name: Checkout the Packages repository alongside the one being compiled
      uses: actions/checkout@v3
      with:
        repository: dgmjr-io/Packages
        path: Packages
    - name: Run setup-dgmjrsdk
      uses: dgmjr-actions/setup-dgmjrsdk@main
      with:
        git-token: ${{ secrets.GITHUB_TOKEN }}
        environment: Release
        git-nuget-endpoint: ${{ vars.GIT_NUGET_ENDPOINT }}
        private-nuget-endpoint: ${{ vars.DGMJR_IO_NUGET_ENDPOINT }}
    - name: Restore dependencies
      run: dotnet restore Repo/src/DgmjrSdk.nuproj
    - name: Build
      run: dotnet build Repo/src/DgmjrSdk.nuproj --no-restore -c:Release -t:PushGitHub
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
